#!/bin/bash

if [ $# < 1 ] ; then
    echo "Usage: invim {new|up}
fi

case $1 in
    new )
        curl http://j.mp/spf13-vim3 -L -o - | sh
    ;;
    up )
        cd $HOME/to/spf13-vim/
        git pull
        vim +BundleInstall! +BundleClean +q
    ;;
esac

