#!/bin/bash

mv /home/ben/.bashrc /home/ben/.bashrc.old
mv /home/ben/.tmux.conf /home/ben/.tmux.conf.old
link -siv /home/ben/conf.mine/.blocals /home/ben/.blocals
link -siv /home/ben/conf.mine/.bashrc /home/ben/.bashrc
link -siv /home/ben/conf.mine/.tmux.conf /home/ben/.tmux.conf
