#!/bin/bash

mv /home/ben/.bashrc /home/ben/.bashrc.old
mv /home/ben/.tmux.conf /home/ben/.tmux.conf.old
ln -siv /home/ben/conf.mine/.blocals /home/ben/.blocals
ln -siv /home/ben/conf.mine/.bashrc /home/ben/.bashrc
ln -siv /home/ben/conf.mine/.tmux.conf /home/ben/.tmux.conf
