#!/bin/bash

# $1 = /home tree
if [ ! $# -eq 1 ]; then
 echo "Please enter a home tree (i.e. linkem /home/ben)"
 exit 0;
fi

mv $1/.bashrc $1/.bashrc.old
mv $1/.tmux.conf $1/.tmux.conf.old
ln -siv $1/conf.mine/.blocals $1/.blocals
ln -siv $1/conf.mine/.bashrc $1/.bashrc
ln -siv $1/conf.mine/.tmux.conf $1/.tmux.conf
